//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("RS2Model", "FK_alliance_users", "users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(RS2.Models.user), "alliance", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RS2.Models.alliance), true)]
[assembly: EdmRelationshipAttribute("RS2Model", "FK_alliance_users1", "users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(RS2.Models.user), "alliance", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RS2.Models.alliance), true)]
[assembly: EdmRelationshipAttribute("RS2Model", "FK_attack_cities", "cities", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(RS2.Models.city), "attack", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RS2.Models.attack), true)]
[assembly: EdmRelationshipAttribute("RS2Model", "FK_attack_cities1", "cities", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(RS2.Models.city), "attack", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RS2.Models.attack), true)]
[assembly: EdmRelationshipAttribute("RS2Model", "FK_city_buildings_buildings", "buildings", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(RS2.Models.building), "city_buildings", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RS2.Models.city_buildings), true)]
[assembly: EdmRelationshipAttribute("RS2Model", "FK_cities_city_types", "city_types", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(RS2.Models.city_types), "cities", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RS2.Models.city), true)]
[assembly: EdmRelationshipAttribute("RS2Model", "FK_city_buildings_cities", "cities", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(RS2.Models.city), "city_buildings", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RS2.Models.city_buildings), true)]
[assembly: EdmRelationshipAttribute("RS2Model", "FK_users_cities_cities", "cities", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(RS2.Models.city), "user_cities", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RS2.Models.user_cities), true)]
[assembly: EdmRelationshipAttribute("RS2Model", "FK_users_cities_users", "users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(RS2.Models.user), "user_cities", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RS2.Models.user_cities), true)]

#endregion

namespace RS2.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class RS2Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new RS2Entities object using the connection string found in the 'RS2Entities' section of the application configuration file.
        /// </summary>
        public RS2Entities() : base("name=RS2Entities", "RS2Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RS2Entities object.
        /// </summary>
        public RS2Entities(string connectionString) : base(connectionString, "RS2Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RS2Entities object.
        /// </summary>
        public RS2Entities(EntityConnection connection) : base(connection, "RS2Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<alliance> alliances
        {
            get
            {
                if ((_alliances == null))
                {
                    _alliances = base.CreateObjectSet<alliance>("alliances");
                }
                return _alliances;
            }
        }
        private ObjectSet<alliance> _alliances;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<attack> attacks
        {
            get
            {
                if ((_attacks == null))
                {
                    _attacks = base.CreateObjectSet<attack>("attacks");
                }
                return _attacks;
            }
        }
        private ObjectSet<attack> _attacks;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<building> buildings
        {
            get
            {
                if ((_buildings == null))
                {
                    _buildings = base.CreateObjectSet<building>("buildings");
                }
                return _buildings;
            }
        }
        private ObjectSet<building> _buildings;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<city> cities
        {
            get
            {
                if ((_cities == null))
                {
                    _cities = base.CreateObjectSet<city>("cities");
                }
                return _cities;
            }
        }
        private ObjectSet<city> _cities;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<city_buildings> city_buildings
        {
            get
            {
                if ((_city_buildings == null))
                {
                    _city_buildings = base.CreateObjectSet<city_buildings>("city_buildings");
                }
                return _city_buildings;
            }
        }
        private ObjectSet<city_buildings> _city_buildings;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<city_types> city_types
        {
            get
            {
                if ((_city_types == null))
                {
                    _city_types = base.CreateObjectSet<city_types>("city_types");
                }
                return _city_types;
            }
        }
        private ObjectSet<city_types> _city_types;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<user_cities> user_cities
        {
            get
            {
                if ((_user_cities == null))
                {
                    _user_cities = base.CreateObjectSet<user_cities>("user_cities");
                }
                return _user_cities;
            }
        }
        private ObjectSet<user_cities> _user_cities;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<user> users
        {
            get
            {
                if ((_users == null))
                {
                    _users = base.CreateObjectSet<user>("users");
                }
                return _users;
            }
        }
        private ObjectSet<user> _users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the alliances EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToalliances(alliance alliance)
        {
            base.AddObject("alliances", alliance);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the attacks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToattacks(attack attack)
        {
            base.AddObject("attacks", attack);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the buildings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTobuildings(building building)
        {
            base.AddObject("buildings", building);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the cities EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocities(city city)
        {
            base.AddObject("cities", city);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the city_buildings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocity_buildings(city_buildings city_buildings)
        {
            base.AddObject("city_buildings", city_buildings);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the city_types EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocity_types(city_types city_types)
        {
            base.AddObject("city_types", city_types);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the user_cities EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTouser_cities(user_cities user_cities)
        {
            base.AddObject("user_cities", user_cities);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTousers(user user)
        {
            base.AddObject("users", user);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RS2Model", Name="alliance")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class alliance : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new alliance object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="user1_id">Initial value of the user1_id property.</param>
        /// <param name="user2_id">Initial value of the user2_id property.</param>
        public static alliance Createalliance(global::System.Int32 id, global::System.Int32 user1_id, global::System.Int32 user2_id)
        {
            alliance alliance = new alliance();
            alliance.id = id;
            alliance.user1_id = user1_id;
            alliance.user2_id = user2_id;
            return alliance;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 user1_id
        {
            get
            {
                return _user1_id;
            }
            set
            {
                Onuser1_idChanging(value);
                ReportPropertyChanging("user1_id");
                _user1_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("user1_id");
                Onuser1_idChanged();
            }
        }
        private global::System.Int32 _user1_id;
        partial void Onuser1_idChanging(global::System.Int32 value);
        partial void Onuser1_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 user2_id
        {
            get
            {
                return _user2_id;
            }
            set
            {
                Onuser2_idChanging(value);
                ReportPropertyChanging("user2_id");
                _user2_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("user2_id");
                Onuser2_idChanged();
            }
        }
        private global::System.Int32 _user2_id;
        partial void Onuser2_idChanging(global::System.Int32 value);
        partial void Onuser2_idChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RS2Model", "FK_alliance_users", "users")]
        public user user
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("RS2Model.FK_alliance_users", "users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("RS2Model.FK_alliance_users", "users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<user> userReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("RS2Model.FK_alliance_users", "users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<user>("RS2Model.FK_alliance_users", "users", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RS2Model", "FK_alliance_users1", "users")]
        public user user1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("RS2Model.FK_alliance_users1", "users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("RS2Model.FK_alliance_users1", "users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<user> user1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("RS2Model.FK_alliance_users1", "users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<user>("RS2Model.FK_alliance_users1", "users", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RS2Model", Name="attack")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class attack : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new attack object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="attacker_city_id">Initial value of the attacker_city_id property.</param>
        /// <param name="defender_city_id">Initial value of the defender_city_id property.</param>
        /// <param name="attack_time">Initial value of the attack_time property.</param>
        public static attack Createattack(global::System.Int32 id, global::System.Int32 attacker_city_id, global::System.Int32 defender_city_id, global::System.DateTime attack_time)
        {
            attack attack = new attack();
            attack.id = id;
            attack.attacker_city_id = attacker_city_id;
            attack.defender_city_id = defender_city_id;
            attack.attack_time = attack_time;
            return attack;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 attacker_city_id
        {
            get
            {
                return _attacker_city_id;
            }
            set
            {
                Onattacker_city_idChanging(value);
                ReportPropertyChanging("attacker_city_id");
                _attacker_city_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("attacker_city_id");
                Onattacker_city_idChanged();
            }
        }
        private global::System.Int32 _attacker_city_id;
        partial void Onattacker_city_idChanging(global::System.Int32 value);
        partial void Onattacker_city_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 defender_city_id
        {
            get
            {
                return _defender_city_id;
            }
            set
            {
                Ondefender_city_idChanging(value);
                ReportPropertyChanging("defender_city_id");
                _defender_city_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("defender_city_id");
                Ondefender_city_idChanged();
            }
        }
        private global::System.Int32 _defender_city_id;
        partial void Ondefender_city_idChanging(global::System.Int32 value);
        partial void Ondefender_city_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime attack_time
        {
            get
            {
                return _attack_time;
            }
            set
            {
                Onattack_timeChanging(value);
                ReportPropertyChanging("attack_time");
                _attack_time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("attack_time");
                Onattack_timeChanged();
            }
        }
        private global::System.DateTime _attack_time;
        partial void Onattack_timeChanging(global::System.DateTime value);
        partial void Onattack_timeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RS2Model", "FK_attack_cities", "cities")]
        public city city
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<city>("RS2Model.FK_attack_cities", "cities").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<city>("RS2Model.FK_attack_cities", "cities").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<city> cityReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<city>("RS2Model.FK_attack_cities", "cities");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<city>("RS2Model.FK_attack_cities", "cities", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RS2Model", "FK_attack_cities1", "cities")]
        public city city1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<city>("RS2Model.FK_attack_cities1", "cities").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<city>("RS2Model.FK_attack_cities1", "cities").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<city> city1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<city>("RS2Model.FK_attack_cities1", "cities");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<city>("RS2Model.FK_attack_cities1", "cities", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RS2Model", Name="building")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class building : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new building object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="base_food_production">Initial value of the base_food_production property.</param>
        /// <param name="base_money_production">Initial value of the base_money_production property.</param>
        /// <param name="base_materials_production">Initial value of the base_materials_production property.</param>
        /// <param name="base_army_producton">Initial value of the base_army_producton property.</param>
        /// <param name="base_food_cost">Initial value of the base_food_cost property.</param>
        /// <param name="base_money_cost">Initial value of the base_money_cost property.</param>
        /// <param name="base_materials_cost">Initial value of the base_materials_cost property.</param>
        public static building Createbuilding(global::System.Int32 id, global::System.String name, global::System.Double base_food_production, global::System.Double base_money_production, global::System.Double base_materials_production, global::System.Double base_army_producton, global::System.Double base_food_cost, global::System.Double base_money_cost, global::System.Double base_materials_cost)
        {
            building building = new building();
            building.id = id;
            building.name = name;
            building.base_food_production = base_food_production;
            building.base_money_production = base_money_production;
            building.base_materials_production = base_materials_production;
            building.base_army_producton = base_army_producton;
            building.base_food_cost = base_food_cost;
            building.base_money_cost = base_money_cost;
            building.base_materials_cost = base_materials_cost;
            return building;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double base_food_production
        {
            get
            {
                return _base_food_production;
            }
            set
            {
                Onbase_food_productionChanging(value);
                ReportPropertyChanging("base_food_production");
                _base_food_production = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("base_food_production");
                Onbase_food_productionChanged();
            }
        }
        private global::System.Double _base_food_production;
        partial void Onbase_food_productionChanging(global::System.Double value);
        partial void Onbase_food_productionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double base_money_production
        {
            get
            {
                return _base_money_production;
            }
            set
            {
                Onbase_money_productionChanging(value);
                ReportPropertyChanging("base_money_production");
                _base_money_production = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("base_money_production");
                Onbase_money_productionChanged();
            }
        }
        private global::System.Double _base_money_production;
        partial void Onbase_money_productionChanging(global::System.Double value);
        partial void Onbase_money_productionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double base_materials_production
        {
            get
            {
                return _base_materials_production;
            }
            set
            {
                Onbase_materials_productionChanging(value);
                ReportPropertyChanging("base_materials_production");
                _base_materials_production = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("base_materials_production");
                Onbase_materials_productionChanged();
            }
        }
        private global::System.Double _base_materials_production;
        partial void Onbase_materials_productionChanging(global::System.Double value);
        partial void Onbase_materials_productionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double base_army_producton
        {
            get
            {
                return _base_army_producton;
            }
            set
            {
                Onbase_army_productonChanging(value);
                ReportPropertyChanging("base_army_producton");
                _base_army_producton = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("base_army_producton");
                Onbase_army_productonChanged();
            }
        }
        private global::System.Double _base_army_producton;
        partial void Onbase_army_productonChanging(global::System.Double value);
        partial void Onbase_army_productonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double base_food_cost
        {
            get
            {
                return _base_food_cost;
            }
            set
            {
                Onbase_food_costChanging(value);
                ReportPropertyChanging("base_food_cost");
                _base_food_cost = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("base_food_cost");
                Onbase_food_costChanged();
            }
        }
        private global::System.Double _base_food_cost;
        partial void Onbase_food_costChanging(global::System.Double value);
        partial void Onbase_food_costChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double base_money_cost
        {
            get
            {
                return _base_money_cost;
            }
            set
            {
                Onbase_money_costChanging(value);
                ReportPropertyChanging("base_money_cost");
                _base_money_cost = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("base_money_cost");
                Onbase_money_costChanged();
            }
        }
        private global::System.Double _base_money_cost;
        partial void Onbase_money_costChanging(global::System.Double value);
        partial void Onbase_money_costChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double base_materials_cost
        {
            get
            {
                return _base_materials_cost;
            }
            set
            {
                Onbase_materials_costChanging(value);
                ReportPropertyChanging("base_materials_cost");
                _base_materials_cost = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("base_materials_cost");
                Onbase_materials_costChanged();
            }
        }
        private global::System.Double _base_materials_cost;
        partial void Onbase_materials_costChanging(global::System.Double value);
        partial void Onbase_materials_costChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RS2Model", "FK_city_buildings_buildings", "city_buildings")]
        public EntityCollection<city_buildings> city_buildings
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<city_buildings>("RS2Model.FK_city_buildings_buildings", "city_buildings");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<city_buildings>("RS2Model.FK_city_buildings_buildings", "city_buildings", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RS2Model", Name="city")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class city : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new city object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="food">Initial value of the food property.</param>
        /// <param name="money">Initial value of the money property.</param>
        /// <param name="materials">Initial value of the materials property.</param>
        /// <param name="army">Initial value of the army property.</param>
        /// <param name="city_type">Initial value of the city_type property.</param>
        /// <param name="position_row">Initial value of the position_row property.</param>
        /// <param name="position_column">Initial value of the position_column property.</param>
        public static city Createcity(global::System.Int32 id, global::System.Double food, global::System.Double money, global::System.Double materials, global::System.Double army, global::System.Int32 city_type, global::System.Int32 position_row, global::System.Int32 position_column)
        {
            city city = new city();
            city.id = id;
            city.food = food;
            city.money = money;
            city.materials = materials;
            city.army = army;
            city.city_type = city_type;
            city.position_row = position_row;
            city.position_column = position_column;
            return city;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double food
        {
            get
            {
                return _food;
            }
            set
            {
                OnfoodChanging(value);
                ReportPropertyChanging("food");
                _food = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("food");
                OnfoodChanged();
            }
        }
        private global::System.Double _food;
        partial void OnfoodChanging(global::System.Double value);
        partial void OnfoodChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double money
        {
            get
            {
                return _money;
            }
            set
            {
                OnmoneyChanging(value);
                ReportPropertyChanging("money");
                _money = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("money");
                OnmoneyChanged();
            }
        }
        private global::System.Double _money;
        partial void OnmoneyChanging(global::System.Double value);
        partial void OnmoneyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double materials
        {
            get
            {
                return _materials;
            }
            set
            {
                OnmaterialsChanging(value);
                ReportPropertyChanging("materials");
                _materials = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("materials");
                OnmaterialsChanged();
            }
        }
        private global::System.Double _materials;
        partial void OnmaterialsChanging(global::System.Double value);
        partial void OnmaterialsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double army
        {
            get
            {
                return _army;
            }
            set
            {
                OnarmyChanging(value);
                ReportPropertyChanging("army");
                _army = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("army");
                OnarmyChanged();
            }
        }
        private global::System.Double _army;
        partial void OnarmyChanging(global::System.Double value);
        partial void OnarmyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 city_type
        {
            get
            {
                return _city_type;
            }
            set
            {
                Oncity_typeChanging(value);
                ReportPropertyChanging("city_type");
                _city_type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("city_type");
                Oncity_typeChanged();
            }
        }
        private global::System.Int32 _city_type;
        partial void Oncity_typeChanging(global::System.Int32 value);
        partial void Oncity_typeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 position_row
        {
            get
            {
                return _position_row;
            }
            set
            {
                Onposition_rowChanging(value);
                ReportPropertyChanging("position_row");
                _position_row = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("position_row");
                Onposition_rowChanged();
            }
        }
        private global::System.Int32 _position_row;
        partial void Onposition_rowChanging(global::System.Int32 value);
        partial void Onposition_rowChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 position_column
        {
            get
            {
                return _position_column;
            }
            set
            {
                Onposition_columnChanging(value);
                ReportPropertyChanging("position_column");
                _position_column = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("position_column");
                Onposition_columnChanged();
            }
        }
        private global::System.Int32 _position_column;
        partial void Onposition_columnChanging(global::System.Int32 value);
        partial void Onposition_columnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RS2Model", "FK_attack_cities", "attack")]
        public EntityCollection<attack> attacks
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<attack>("RS2Model.FK_attack_cities", "attack");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<attack>("RS2Model.FK_attack_cities", "attack", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RS2Model", "FK_attack_cities1", "attack")]
        public EntityCollection<attack> attacks1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<attack>("RS2Model.FK_attack_cities1", "attack");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<attack>("RS2Model.FK_attack_cities1", "attack", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RS2Model", "FK_cities_city_types", "city_types")]
        public city_types city_types
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<city_types>("RS2Model.FK_cities_city_types", "city_types").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<city_types>("RS2Model.FK_cities_city_types", "city_types").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<city_types> city_typesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<city_types>("RS2Model.FK_cities_city_types", "city_types");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<city_types>("RS2Model.FK_cities_city_types", "city_types", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RS2Model", "FK_city_buildings_cities", "city_buildings")]
        public EntityCollection<city_buildings> city_buildings
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<city_buildings>("RS2Model.FK_city_buildings_cities", "city_buildings");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<city_buildings>("RS2Model.FK_city_buildings_cities", "city_buildings", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RS2Model", "FK_users_cities_cities", "user_cities")]
        public EntityCollection<user_cities> user_cities
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<user_cities>("RS2Model.FK_users_cities_cities", "user_cities");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<user_cities>("RS2Model.FK_users_cities_cities", "user_cities", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RS2Model", Name="city_buildings")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class city_buildings : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new city_buildings object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="city_id">Initial value of the city_id property.</param>
        /// <param name="building_id">Initial value of the building_id property.</param>
        /// <param name="lvl">Initial value of the lvl property.</param>
        /// <param name="building_positionX">Initial value of the building_positionX property.</param>
        /// <param name="building_positionY">Initial value of the building_positionY property.</param>
        /// <param name="buildStarted">Initial value of the buildStarted property.</param>
        public static city_buildings Createcity_buildings(global::System.Int32 id, global::System.Int32 city_id, global::System.Int32 building_id, global::System.Int32 lvl, global::System.Int32 building_positionX, global::System.Int32 building_positionY, global::System.DateTime buildStarted)
        {
            city_buildings city_buildings = new city_buildings();
            city_buildings.id = id;
            city_buildings.city_id = city_id;
            city_buildings.building_id = building_id;
            city_buildings.lvl = lvl;
            city_buildings.building_positionX = building_positionX;
            city_buildings.building_positionY = building_positionY;
            city_buildings.buildStarted = buildStarted;
            return city_buildings;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 city_id
        {
            get
            {
                return _city_id;
            }
            set
            {
                Oncity_idChanging(value);
                ReportPropertyChanging("city_id");
                _city_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("city_id");
                Oncity_idChanged();
            }
        }
        private global::System.Int32 _city_id;
        partial void Oncity_idChanging(global::System.Int32 value);
        partial void Oncity_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 building_id
        {
            get
            {
                return _building_id;
            }
            set
            {
                Onbuilding_idChanging(value);
                ReportPropertyChanging("building_id");
                _building_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("building_id");
                Onbuilding_idChanged();
            }
        }
        private global::System.Int32 _building_id;
        partial void Onbuilding_idChanging(global::System.Int32 value);
        partial void Onbuilding_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 lvl
        {
            get
            {
                return _lvl;
            }
            set
            {
                OnlvlChanging(value);
                ReportPropertyChanging("lvl");
                _lvl = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("lvl");
                OnlvlChanged();
            }
        }
        private global::System.Int32 _lvl;
        partial void OnlvlChanging(global::System.Int32 value);
        partial void OnlvlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 building_positionX
        {
            get
            {
                return _building_positionX;
            }
            set
            {
                Onbuilding_positionXChanging(value);
                ReportPropertyChanging("building_positionX");
                _building_positionX = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("building_positionX");
                Onbuilding_positionXChanged();
            }
        }
        private global::System.Int32 _building_positionX;
        partial void Onbuilding_positionXChanging(global::System.Int32 value);
        partial void Onbuilding_positionXChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 building_positionY
        {
            get
            {
                return _building_positionY;
            }
            set
            {
                Onbuilding_positionYChanging(value);
                ReportPropertyChanging("building_positionY");
                _building_positionY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("building_positionY");
                Onbuilding_positionYChanged();
            }
        }
        private global::System.Int32 _building_positionY;
        partial void Onbuilding_positionYChanging(global::System.Int32 value);
        partial void Onbuilding_positionYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> isPending
        {
            get
            {
                return _isPending;
            }
            set
            {
                OnisPendingChanging(value);
                ReportPropertyChanging("isPending");
                _isPending = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isPending");
                OnisPendingChanged();
            }
        }
        private Nullable<global::System.Int32> _isPending;
        partial void OnisPendingChanging(Nullable<global::System.Int32> value);
        partial void OnisPendingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime buildStarted
        {
            get
            {
                return _buildStarted;
            }
            set
            {
                OnbuildStartedChanging(value);
                ReportPropertyChanging("buildStarted");
                _buildStarted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("buildStarted");
                OnbuildStartedChanged();
            }
        }
        private global::System.DateTime _buildStarted;
        partial void OnbuildStartedChanging(global::System.DateTime value);
        partial void OnbuildStartedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> buildTime
        {
            get
            {
                return _buildTime;
            }
            set
            {
                OnbuildTimeChanging(value);
                ReportPropertyChanging("buildTime");
                _buildTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("buildTime");
                OnbuildTimeChanged();
            }
        }
        private Nullable<global::System.Int32> _buildTime;
        partial void OnbuildTimeChanging(Nullable<global::System.Int32> value);
        partial void OnbuildTimeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RS2Model", "FK_city_buildings_buildings", "buildings")]
        public building building
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<building>("RS2Model.FK_city_buildings_buildings", "buildings").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<building>("RS2Model.FK_city_buildings_buildings", "buildings").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<building> buildingReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<building>("RS2Model.FK_city_buildings_buildings", "buildings");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<building>("RS2Model.FK_city_buildings_buildings", "buildings", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RS2Model", "FK_city_buildings_cities", "cities")]
        public city city
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<city>("RS2Model.FK_city_buildings_cities", "cities").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<city>("RS2Model.FK_city_buildings_cities", "cities").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<city> cityReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<city>("RS2Model.FK_city_buildings_cities", "cities");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<city>("RS2Model.FK_city_buildings_cities", "cities", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RS2Model", Name="city_types")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class city_types : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new city_types object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="food_multi">Initial value of the food_multi property.</param>
        /// <param name="money_multi">Initial value of the money_multi property.</param>
        /// <param name="materials_multi">Initial value of the materials_multi property.</param>
        /// <param name="army_multi">Initial value of the army_multi property.</param>
        public static city_types Createcity_types(global::System.Int32 id, global::System.Double food_multi, global::System.Double money_multi, global::System.Double materials_multi, global::System.Double army_multi)
        {
            city_types city_types = new city_types();
            city_types.id = id;
            city_types.food_multi = food_multi;
            city_types.money_multi = money_multi;
            city_types.materials_multi = materials_multi;
            city_types.army_multi = army_multi;
            return city_types;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double food_multi
        {
            get
            {
                return _food_multi;
            }
            set
            {
                Onfood_multiChanging(value);
                ReportPropertyChanging("food_multi");
                _food_multi = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("food_multi");
                Onfood_multiChanged();
            }
        }
        private global::System.Double _food_multi;
        partial void Onfood_multiChanging(global::System.Double value);
        partial void Onfood_multiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double money_multi
        {
            get
            {
                return _money_multi;
            }
            set
            {
                Onmoney_multiChanging(value);
                ReportPropertyChanging("money_multi");
                _money_multi = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("money_multi");
                Onmoney_multiChanged();
            }
        }
        private global::System.Double _money_multi;
        partial void Onmoney_multiChanging(global::System.Double value);
        partial void Onmoney_multiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double materials_multi
        {
            get
            {
                return _materials_multi;
            }
            set
            {
                Onmaterials_multiChanging(value);
                ReportPropertyChanging("materials_multi");
                _materials_multi = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("materials_multi");
                Onmaterials_multiChanged();
            }
        }
        private global::System.Double _materials_multi;
        partial void Onmaterials_multiChanging(global::System.Double value);
        partial void Onmaterials_multiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double army_multi
        {
            get
            {
                return _army_multi;
            }
            set
            {
                Onarmy_multiChanging(value);
                ReportPropertyChanging("army_multi");
                _army_multi = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("army_multi");
                Onarmy_multiChanged();
            }
        }
        private global::System.Double _army_multi;
        partial void Onarmy_multiChanging(global::System.Double value);
        partial void Onarmy_multiChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RS2Model", "FK_cities_city_types", "cities")]
        public EntityCollection<city> cities
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<city>("RS2Model.FK_cities_city_types", "cities");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<city>("RS2Model.FK_cities_city_types", "cities", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RS2Model", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RS2Model", Name="user")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class user : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new user object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="username">Initial value of the username property.</param>
        /// <param name="password">Initial value of the password property.</param>
        /// <param name="nickname">Initial value of the nickname property.</param>
        public static user Createuser(global::System.Int32 id, global::System.String username, global::System.String password, global::System.String nickname)
        {
            user user = new user();
            user.id = id;
            user.username = username;
            user.password = password;
            user.nickname = nickname;
            return user;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String username
        {
            get
            {
                return _username;
            }
            set
            {
                OnusernameChanging(value);
                ReportPropertyChanging("username");
                _username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("username");
                OnusernameChanged();
            }
        }
        private global::System.String _username;
        partial void OnusernameChanging(global::System.String value);
        partial void OnusernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nickname
        {
            get
            {
                return _nickname;
            }
            set
            {
                OnnicknameChanging(value);
                ReportPropertyChanging("nickname");
                _nickname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nickname");
                OnnicknameChanged();
            }
        }
        private global::System.String _nickname;
        partial void OnnicknameChanging(global::System.String value);
        partial void OnnicknameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RS2Model", "FK_alliance_users", "alliance")]
        public EntityCollection<alliance> alliances
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<alliance>("RS2Model.FK_alliance_users", "alliance");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<alliance>("RS2Model.FK_alliance_users", "alliance", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RS2Model", "FK_alliance_users1", "alliance")]
        public EntityCollection<alliance> alliances1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<alliance>("RS2Model.FK_alliance_users1", "alliance");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<alliance>("RS2Model.FK_alliance_users1", "alliance", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RS2Model", "FK_users_cities_users", "user_cities")]
        public EntityCollection<user_cities> user_cities
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<user_cities>("RS2Model.FK_users_cities_users", "user_cities");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<user_cities>("RS2Model.FK_users_cities_users", "user_cities", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RS2Model", Name="user_cities")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class user_cities : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new user_cities object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="user_id">Initial value of the user_id property.</param>
        /// <param name="city_id">Initial value of the city_id property.</param>
        public static user_cities Createuser_cities(global::System.Int32 id, global::System.Int32 user_id, global::System.Int32 city_id)
        {
            user_cities user_cities = new user_cities();
            user_cities.id = id;
            user_cities.user_id = user_id;
            user_cities.city_id = city_id;
            return user_cities;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 user_id
        {
            get
            {
                return _user_id;
            }
            set
            {
                Onuser_idChanging(value);
                ReportPropertyChanging("user_id");
                _user_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("user_id");
                Onuser_idChanged();
            }
        }
        private global::System.Int32 _user_id;
        partial void Onuser_idChanging(global::System.Int32 value);
        partial void Onuser_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 city_id
        {
            get
            {
                return _city_id;
            }
            set
            {
                Oncity_idChanging(value);
                ReportPropertyChanging("city_id");
                _city_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("city_id");
                Oncity_idChanged();
            }
        }
        private global::System.Int32 _city_id;
        partial void Oncity_idChanging(global::System.Int32 value);
        partial void Oncity_idChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RS2Model", "FK_users_cities_cities", "cities")]
        public city city
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<city>("RS2Model.FK_users_cities_cities", "cities").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<city>("RS2Model.FK_users_cities_cities", "cities").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<city> cityReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<city>("RS2Model.FK_users_cities_cities", "cities");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<city>("RS2Model.FK_users_cities_cities", "cities", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RS2Model", "FK_users_cities_users", "users")]
        public user user
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("RS2Model.FK_users_cities_users", "users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("RS2Model.FK_users_cities_users", "users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<user> userReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("RS2Model.FK_users_cities_users", "users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<user>("RS2Model.FK_users_cities_users", "users", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
